name: p_utils
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - bcrypt=5.0.0
  - black=26.1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - cryptography=46.0.5
  - cyrus-sasl=2.1.28
  - daiquiri=3.0.0
  - docopt=0.6.2
  - frozenlist=1.7.0
  - greenlet=3.3.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - invoke=2.2.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45.1
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.2
  - libnsl=2.0.1
  - libntlm=1.8
  - libpq=18.1
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - multidict=6.7.0
  - mypy_extensions=1.1.0
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.6.1
  - packaging=26.0
  - paramiko=4.0.0
  - pathspec=1.0.4
  - pip=26.0.1
  - platformdirs=4.5.1
  - propcache=0.3.1
  - psycopg2=2.9.11
  - pycparser=2.22
  - pynacl=1.6.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytokens=0.4.1
  - readline=8.3
  - requests=2.32.5
  - setuptools=82.0.0
  - six=1.17.0
  - sqlalchemy=1.4.49
  - tk=8.6.13
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wheel=0.46.3
  - yarl=1.22.0
  - zstd=1.5.7
prefix: /home/servilla/miniconda3/envs/p_utils
