name: p_utils
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - attrs=25.4.0
  - bcrypt=5.0.0
  - black=25.1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - colorama=0.4.6
  - cryptography=46.0.3
  - cyrus-sasl=2.1.28
  - daiquiri=3.0.0
  - docopt=0.6.2
  - frozenlist=1.7.0
  - greenlet=3.2.4
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - invoke=2.2.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libpq=18.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - multidict=6.6.3
  - mypy_extensions=1.1.0
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=25.0
  - paramiko=4.0.0
  - pathspec=0.12.1
  - pip=25.2
  - platformdirs=4.5.0
  - propcache=0.3.1
  - psycopg2=2.9.10
  - pycparser=2.22
  - pynacl=1.6.0
  - pysocks=1.7.1
  - python=3.12.12
  - python-json-logger=2.0.7
  - python_abi=3.12
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=1.4.49
  - tk=8.6.13
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - yarl=1.22.0
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/servilla/miniconda3/envs/p_utils
